アラートの作成
shimamaru/shimamaru-frontend-basic-2022-todoapp pull request #12
Opened 2023-03-18 03:33 UTC by shimamaru

2023-03-18 04:08 UTC, minezaki-mutsuki reviewed
organisms/todoCardの中で、valueが空文字のときにタスク名が変わるところの処理にcontextを呼び出す処理が必要だと思います

2023-03-18 04:08 UTC, minezaki-mutsuki commented on src/components/contexts/alert_handler.jsx
> +    setAlertState({ visible: true, message });
引数で受け取ったものをセットするには`message: message,`だと思います

2023-03-18 04:08 UTC, minezaki-mutsuki commented on src/components/Organisms/AlertManager/index.jsx
> +  return <div>{visible && <Alert show={visible} message={message} />}</div>;
`visible &&`はいらないです（見えるかどうかの指示は`show={visible}`で渡してる時点でAlertコンポーネントがやってくれる）
あと、divもいらないと思います。
また、messageをpropsで渡すならばatomsのalertコンポーネントに引数としてmessageを追加する必要があります。

2023-03-18 04:08 UTC, minezaki-mutsuki commented on src/components/Atoms/Alert/index.jsx
> +  return <StyledAlert show={show}>警告</StyledAlert>;
alertManagerでmessageを受け取るようにしているので、こっちでは引数が必要になります。引数messageはこんな感じで表示するようにするといいと思います
`<StyledAlert>{message}</StyledAlert>`

2023-03-19 01:35 UTC, higashiji2000 requested changes
秒数の変更だけお願いします！

2023-03-19 01:35 UTC, higashiji2000 commented on src/components/Organisms/AlertManager/index.jsx
> +      }, 500000);
> delay 省略可
指定した関数やコードを実行する前に待つタイマーの時間をミリ秒 (1/1000 秒) 単位で指定します。この引数を省略すると値 0 を使用しますので "直ちに" 実行する、より正確に言えばできるだけ早く実行することを意味します。


現状500秒になっていそうです

2023-03-20 11:22 UTC, higashiji2000 approved these changes
LGTMです！！
↓で動作確認済みです。
https://shimamaru.github.io/shimamaru-frontend-basic-2022-todoapp/

2023-03-20 11:22 UTC, higashiji2000 commented on src/components/Organisms/AlertManager/index.jsx
> +      }, 5000);
```suggestion
const ALERT_DURATION_MS = 5000;

const AlertManager = () => {
  const { visible, message, closeAlert } = useAlertHandlerContext();

  useEffect(() => {
    if (visible) {
      const timer = setTimeout(() => {
        closeAlert();
      }, ALERT_DURATION_MS);
```

こんな感じで定数化すると可読性が上がると言われています！
マジックナンバーをへらすということを意識してみるのがおすすめです。

2023-04-03 05:49 UTC, merged