atoms/EditButtonの作成
shimamaru/shimamaru-frontend-basic-2022-todoapp pull request #2
Opened 2022-12-27 01:00 UTC by shimamaru

2022-12-29 13:28 UTC, minezaki-mutsuki reviewed
reactとしての挙動は良いと思いますー
見た目の方だけ修正お願いします

2022-12-29 13:28 UTC, minezaki-mutsuki commented on src/components/Example/EditButton/index.jsx
> +    background-color: #dcdcdc;
色は変数で書いてほしいです。`src/variables/color.js`にあります。

2022-12-29 13:28 UTC, minezaki-mutsuki commented on src/components/Example/EditButton/index.jsx
> +const StyledButton = styled.button`
buttonタグの影響か、四角い背景が表示されてるので消しておいてください。
![スクリーンショット (161)](https://user-images.githubusercontent.com/83950556/209959576-c711eb2b-13e7-44c0-b028-7a1bba2a3123.png)

2022-12-30 02:31 UTC, shimamaru commented on src/components/Example/EditButton/index.jsx
> +    background-color: #dcdcdc;
この色はfigamから採用したのですが、variablesのファイルの中に変数として用意されてないです。
ですから、colorpickerというchormeの機能から勝手に引っ張ってきました。
変数としてあらかじめ用意されていないのでどうすれば良いのでしょうか？

2022-12-31 06:09 UTC, KEISUKE0293 reviewed
ボタン全体の背景色は透過されている方が良いかもしれません。

2022-12-31 06:09 UTC, KEISUKE0293 commented on src/components/Example/EditButton/index.jsx
> +    background-color: #dcdcdc;
ここでの背景色は#dcdcdcではないはずです！もう一度figmaで確認してください！

2023-01-12 11:23 UTC, higashiji2000 requested changes
名称未設定フォルダが追加されてしまっているので、削除お願いします。
また、ついでにホバー時のカーソルをpointerにしてあげるとよりクオリティが高いものになると思います。

2023-01-12 12:26 UTC, higashiji2000 approved these changes
LGTMです 🐝

2023-01-12 12:32 UTC, merged