atoms/AddTaskButtonの作成
shimamaru/shimamaru-frontend-basic-2022-todoapp pull request #3
Opened 2022-12-27 09:43 UTC by shimamaru

2022-12-29 13:35 UTC, minezaki-mutsuki commented on src/components/Example/AddTaskButton/story.jsx
> +Default.args = {};
index.jsxで設定したpropsをstory側から渡してあげてほしいです（storybook側で一応挙動を確認した方がいいので）

2023-01-03 06:54 UTC, Hasegawa62 reviewed
ディレクトリ構造が間違っているようです。
(そのためstorybookでもAddTaskButtonを確認できていません。)
課題ページを参考に修正お願いします！

2023-01-03 06:54 UTC, Hasegawa62 commented on src/components/Example/AddTaskButton/story.jsx
> +export const Default = Template.bind({});
mutsukiさんが指摘していたのは、課題ページのここにあたる部分だと思います。
http://shinonome.io/frontend-basic-2022-textbook/atoms-editbutton#:~:text=%E5%85%88%E3%81%BB%E3%81%A9story.jsx,%E6%8C%87%E5%AE%9A%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82
これを書き足すと、storybook上でボタンをクリックしたときにコンソールで"clicked"が出るようになり、上手くonClickのpropsが機能しているかどうか確認ができます。
課題ページではAtoms/EditButtonだけで言及されていますが、他のコンポーネント作成時でもpropsを使うときは設定してあると確認しやすくて良いです◎

2023-01-12 13:15 UTC, higashiji2000 requested changes
ほとんどOKです！スタイルに関して2点確認お願いします。

2023-01-12 13:15 UTC, higashiji2000 commented on src/components/Atoms/AddTaskButton/index.jsx
> +    background-color: #c5d8d2;
<img width="195" alt="image" src="https://user-images.githubusercontent.com/83479175/212074809-9c19fc46-bb79-4634-9c4f-bedd0073a150.png">
<img width="136" alt="image" src="https://user-images.githubusercontent.com/83479175/212075195-8f7a8ac4-67f8-4bb8-860a-501f0400ec61.png">

hover時の色が[完成形](http://shinonome.io/frontend-basic-2022-todoapp/)と違うので確認お願いします！
こちらも EditButton と同じように opacity の設定を要するので、別の要素として作成する必要があるかもしれません。

2023-01-12 13:15 UTC, higashiji2000 commented on src/components/Atoms/AddTaskButton/index.jsx
> +`;
fontsizeがfigmaより大きいので確認お願いします！

2023-01-14 03:15 UTC, higashiji2000 approved these changes
LGTMです🎿

2023-01-14 03:32 UTC, merged