atoms/Checkboxの作成
shimamaru/shimamaru-frontend-basic-2022-todoapp pull request #4
Opened 2022-12-31 07:10 UTC by shimamaru

ホバー時の軌道をdisplayプロパティやvisibilityプロパティを使って実装を試みましたが、どちらも表示の方がうまくいきませんでした。
ホバー範囲が狭いことが原因のようですが、要素自体の範囲は自分の想定したものと違いません。
この点に関してアドバイスを頂きたいです。

2023-01-02 02:55 UTC, higashiji2000 commented on src/components/Example/Checkbox/index.jsx
> +  }
visibility: hiddenの要素にはhoverできないことが原因のようです。
StyledCheckBoxがホバーされた時にCheckMarkImgをvisibility: hiddenにするように変更が必要だと思います！

2023-01-12 12:38 UTC, higashiji2000 requested changes

2023-01-12 12:38 UTC, higashiji2000 commented on src/components/Example/Checkbox/index.jsx
> +const StyleCheckbox = styled.button`
button要素にデフォルトでついている灰色のbackgroundが適用されてしまっているので、背景に transparent を設定してください。

2023-01-12 12:38 UTC, higashiji2000 commented on src/components/Example/Checkbox/index.jsx
> +`;
<img width="54" alt="image" src="https://user-images.githubusercontent.com/83479175/212067522-31040046-b25a-4b82-9cc0-33c57652644b.png">
チェックマークがお手本より小さいので確認お願いします。

<img width="346" alt="image" src="https://user-images.githubusercontent.com/83479175/212067698-255df14a-0442-47fc-af31-670333fb74ee.png">
原因としては、画像のソース自体に余白が設定されてしまっているからです。
余白込みで 13 × 10 になっている感じです。
figmaの見た目に近づくよう調整お願いします。

2023-01-12 12:38 UTC, higashiji2000 commented on src/components/Example/Checkbox/index.jsx
> +const StyleCheckbox = styled.button`
[完成形](http://shinonome.io/frontend-basic-2022-todoapp/)をみながら作っていくのがお勧めです。

2023-01-13 09:00 UTC, shimamaru commented on src/components/Example/Checkbox/index.jsx
> +`;
数値で調節する方法がわからなかったため目視で確認できる範囲で修正を行いました。
数値で調整できる方法がありましたら教えてください。

2023-01-14 03:24 UTC, higashiji2000 commented on src/components/Example/Checkbox/index.jsx
> +`;
![image](https://user-images.githubusercontent.com/83479175/212448574-96d78132-f77f-4512-ab9f-b45c1ba1fa3c.png)
最終的には目視で問題ないと思います。
自分でしたら上の画像の `done_black_24dp 1` という要素を目安にするかもです。（上下に余白が入った正方形ということで、ソースとほぼ同じだと思います。）

2023-01-14 03:28 UTC, higashiji2000 approved these changes
基本的にOKです！
二点コメント＆approveしてあるので、修正次第マージしてしまってください。

2023-01-14 03:28 UTC, higashiji2000 commented on src/components/Atoms/Checkbox/story.jsx
> +Default.args = {};
onClickに適当なログ出力を渡しておくと、onClickというPropsがちゃんと発火することが確認できるのでより良いです。

2023-01-14 03:28 UTC, higashiji2000 commented on src/components/Atoms/Checkbox/index.jsx
> +  border: 1px solid ${COLOR.LIGHT_GRAY};
```suggestion
  border: 2px solid ${COLOR.LIGHT_GRAY};
```

2023-01-15 11:47 UTC, MoAI522 approved these changes
LGTM

2023-01-15 11:48 UTC, merged